baseURL = "https://diegolinkk.github.io"
languageCode = "pt-br"
title = "Diegolinkk"
theme = "ananke"
googleAnalytics = "UA-157713281-1"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4
  

[taxonomies]
  tag = "tags"

[menu]
[[menu.main]]
  identifier = 'about'
  name = 'Sobre mim'
  pre = "<i class='fa fa-heart'></i>"
  url = '/about/'

[[menu.main]]
  identifier = 'colinha'
  name = 'colinha de comandos'
  url = '/colinha/'