baseURL = "https://diegolinkk.github.io"
languageCode = "pt-br"
title = "Diegolinkk"
theme = "ananke"
googleAnalytics = "UA-157713281-1"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]
  linkedin = "https://www.linkedin.com/in/diego-oliveira-da-silva-269591a9/"
  github = "https://github.com/diegolinkk"

[taxonomies]
  tag = "tags"